import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {createClient } from '@/lib/supabase-server'
import { QueryProvider } from "@/contexts/QueryContext";
import Header from "@/components/pages/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Header user={user} />
          <div className=" flex items-center justify-center bg-gradient-to-br from-blue-900 via-blue-800 to-indigo-900  min-h-screen">
            <div className="max-w-7xl">
              {children}
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
